alias g='grep --color'
alias l='ls -lF --color'
alias la='l -a'
# sort by mod time (t), newest last (r)
alias lt='l -tr'
alias ltf='l -tr --full-time'
# list and sort by creation time
alias lc='l -trc'
alias lcf='l -trc --full-time'
alias psg='ps -e x -o ppid -o pid -o pgid -o tty -o vsz -o rss -o etime -o cputime -o rgroup -o ni -o fname -o args | /boot/bin/grep1'
alias psgc='psg cache_dirs'
alias pstg='pstree1 | grep -2'
alias pst='ps -fja'
alias pstgc='pstree1 | grep -2 cache_dirs'
alias pstg2='pstree -p | grep '
alias pstgc2='pstree -p | grep cache_dirs'
alias tailcachelog='tail -n 2000 -f /var/log/cache_dirs.log'
alias catcachelog='cat /var/log/cache_dirs.log'
alias catcachelog2='cat /var/log/cache_dirs_lost_cache.csv'
alias ptuniq='pstree -p | sed "s/[0-9]//g" | uniq'
alias rpmg='rpm -qa|g '
alias s='less'
alias v='vi'
alias df='df -h'
alias pmem='ps aux | awk "{sum +=\$6}; END {print sum}"'
# diff -ruNp dir1 dir2 | less 
alias mdiff='diff -ruNp'
alias filecount='echo Counting files in `pwd`; find . -type f | wc -l'
# Tell alias-command to check next command after sudo by adding space at end
alias sudo='sudo '
alias docker='sudo docker'
